#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

/**
 * Setup environment files for all services
 */

const ROOT_DIR = path.join(__dirname, '..');

// Determine environment: 'local' for localhost, 'docker' for container names
const ENV_MODE = process.argv.includes('--docker') || process.env.USE_DOCKER_HOSTS === 'true' ? 'docker' : 'local';
// Compact mode: Use a single MongoDB instance for all services in docker
const COMPACT_MODE = process.argv.includes('--compact') || process.env.USE_COMPACT_DB === 'true';

console.log(`\n🔧 Setting up environment files in ${ENV_MODE.toUpperCase()} mode${COMPACT_MODE ? ' (COMPACT)' : ''}...\n`);

// Service configurations with ports and database info
const SERVICE_CONFIGS = {
    'auth-service': {
        port: 3001,
        dbName: 'auth_db',
        mongoPort: 27018
    },
    'subscription-service': {
        port: 3003,
        dbName: 'subscription_db',
        mongoPort: 27020
    },
    'payment-service': {
        port: 3004,
        dbName: 'payment_db',
        mongoPort: 27021
    },
    'notification-service': {
        port: 3008,
        dbName: 'notification_db',
        mongoPort: 27024
    },
    'analytics-service': {
        port: 3009,
        dbName: 'analytics_db',
        mongoPort: 27025
    },
    'support-service': {
        port: 3010,
        dbName: 'support_db',
        mongoPort: 27026
    },
    'media-service': {
        port: 3011,
        dbName: 'media_db',
        mongoPort: 27027
    },
    'chat-service': {
        port: 3012,
        dbName: 'chat_db',
        mongoPort: 27028
    },
    'api-gateway': {
        port: 8000
    }
};

/**
 * Load secrets from .secrets.env if exists
 */
function loadSecrets() {
    const secretsPath = path.join(ROOT_DIR, '.secrets.env');

    if (!fs.existsSync(secretsPath)) {
        console.warn('⚠️  .secrets.env not found. Run "npm run generate:secrets" first.');
        return {};
    }

    const content = fs.readFileSync(secretsPath, 'utf-8');
    const secrets = {};

    content.split('\n').forEach(line => {
        const index = line.indexOf('=');
        if (index > 0) {
            const key = line.substring(0, index).trim();
            const value = line.substring(index + 1).trim();
            if (key && value) {
                // Remove surrounding quotes if present
                secrets[key] = value.replace(/^["'](.*)["']$/, '$1');
            }
        }
    });

    return secrets;
}

/**
 * Generate root .env file
 */
function generateRootEnv(secrets) {
    const envContent = `# Marketplace Platform - Root Environment Configuration
# Generated by setup-env.js

# Environment
NODE_ENV=development

# Kafka Configuration
KAFKA_BROKERS=localhost:9092
KAFKA_CLIENT_ID=marketplace-platform
ZOOKEEPER_HOST=localhost:2181

# Redis Configuration
REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_PASSWORD=${secrets.REDIS_PASSWORD || 'changeme'}

# MongoDB Configuration
MONGODB_HOST=localhost
MONGODB_USER=marketplace_user
MONGODB_PASSWORD=${secrets.MONGODB_PASSWORD || 'changeme'}

# JWT Configuration
JWT_ACCESS_SECRET=${secrets.JWT_ACCESS_SECRET || 'changeme-access-secret'}
JWT_REFRESH_SECRET=${secrets.JWT_REFRESH_SECRET || 'changeme-refresh-secret'}
JWT_ACCESS_EXPIRY=15m
JWT_REFRESH_EXPIRY=7d

# Session Configuration
SESSION_SECRET=${secrets.SESSION_SECRET || 'changeme-session-secret'}

# Email Configuration (SMTP)
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USER=noreply@marketplace.com
SMTP_PASSWORD=changeme
EMAIL_FROM=noreply@marketplace.com

# Twilio Configuration (SMS)
TWILIO_ACCOUNT_SID=your_twilio_account_sid
TWILIO_AUTH_TOKEN=${secrets.TWILIO_AUTH_TOKEN || 'changeme'}
TWILIO_PHONE_NUMBER=+1234567890

# Stripe Configuration
STRIPE_PUBLIC_KEY=pk_test_changeme
STRIPE_SECRET_KEY=${secrets.STRIPE_SECRET_KEY || 'sk_test_changeme'}
STRIPE_WEBHOOK_SECRET=whsec_changeme

# PayPal Configuration
PAYPAL_CLIENT_ID=your_paypal_client_id
PAYPAL_CLIENT_SECRET=${secrets.PAYPAL_CLIENT_SECRET || 'changeme'}
PAYPAL_MODE=sandbox

# AWS S3 Configuration
AWS_REGION=us-east-1
AWS_ACCESS_KEY_ID=your_aws_access_key
AWS_SECRET_ACCESS_KEY=${secrets.AWS_SECRET_ACCESS_KEY || 'changeme'}
AWS_S3_BUCKET=marketplace-media

# CDN Configuration
CDN_URL=https://cdn.marketplace.com

# API Gateway
API_GATEWAY_URL=http://localhost:8000

# Rate Limiting
RATE_LIMIT_WINDOW_MS=900000
RATE_LIMIT_MAX_REQUESTS=100

# Logging
LOG_LEVEL=debug
LOG_DIR=./logs

# External Base URL (for Ngrok/Production)
APP_BASE_URL=${secrets.APP_BASE_URL || 'http://localhost:8000'}

# MongoDB Passwords (for Docker Compose)
MONGODB_PASSWORD_AUTH=${secrets.MONGODB_PASSWORD_AUTH || 'changeme'}
MONGODB_PASSWORD_SUBSCRIPTION=${secrets.MONGODB_PASSWORD_SUBSCRIPTION || 'changeme'}
MONGODB_PASSWORD_PAYMENT=${secrets.MONGODB_PASSWORD_PAYMENT || 'changeme'}
MONGODB_PASSWORD_NOTIFICATION=${secrets.MONGODB_PASSWORD_NOTIFICATION || 'changeme'}
MONGODB_PASSWORD_ANALYTICS=${secrets.MONGODB_PASSWORD_ANALYTICS || 'changeme'}
MONGODB_PASSWORD_SUPPORT=${secrets.MONGODB_PASSWORD_SUPPORT || 'changeme'}
MONGODB_PASSWORD_MEDIA=${secrets.MONGODB_PASSWORD_MEDIA || 'changeme'}
MONGODB_PASSWORD=${secrets.MONGODB_PASSWORD || 'changeme'}


#payunit configuration
PAYUNIT_BASE_URL=${secrets.PAYUNIT_BASE_URL || 'https://gateway.payunit.net'}
PAYUNIT_API_KEY=${secrets.PAYUNIT_API_KEY}
PAYUNIT_API_USERNAME=${secrets.PAYUNIT_API_USERNAME}
PAYUNIT_API_PASSWORD=${secrets.PAYUNIT_API_PASSWORD}
PAYUNIT_MODE=${secrets.PAYUNIT_MODE || 'test'}
PAYUNIT_TIMEOUT=${secrets.PAYUNIT_TIMEOUT || 10000}
PAYUNIT_DEFAULT_CURRENCY=${secrets.PAYUNIT_DEFAULT_CURRENCY || 'XAF'}
PAYUNIT_DEFAULT_COUNTRY=${secrets.PAYUNIT_DEFAULT_COUNTRY || 'CM'} 
`;

    const envPath = path.join(ROOT_DIR, '.env');
    fs.writeFileSync(envPath, envContent);
    console.log('✓ Created root .env file');
}

/**
 * Generate service-specific .env file
 */
function generateServiceEnv(serviceName, config, secrets) {
    const { port, dbName, mongoPort } = config;

    let envContent = `# ${serviceName} - Environment Configuration
# Generated by setup-env.js

# Service Configuration
NODE_ENV=development
PORT=${port}
SERVICE_NAME=${serviceName}

`;

    // Database configuration (Now always MongoDB)
    if (dbName) {
        const mongoPassKey = `MONGODB_PASSWORD_${serviceName.replace('-service', '').toUpperCase()}`;

        let mongoHost;
        let mongoPortForUri;

        if (ENV_MODE === 'docker') {
            if (COMPACT_MODE) {
                mongoHost = 'mongodb-common';
                mongoPortForUri = 27017;
            } else {
                mongoHost = `mongodb-${serviceName.replace('-service', '')}`;
                mongoPortForUri = 27017;
            }
        } else {
            mongoHost = 'localhost';
            mongoPortForUri = mongoPort || 27017;
        }

        envContent += `# MongoDB Configuration
MONGODB_URI=mongodb://marketplace_user:${secrets[mongoPassKey] || secrets.MONGODB_PASSWORD || 'changeme'}@${mongoHost}:${mongoPortForUri}/${dbName}?authSource=admin
MONGODB_DB_NAME=${dbName}

`;
    }

    // Common configurations
    const redisHost = ENV_MODE === 'docker' ? 'redis' : 'localhost';
    const kafkaBrokers = ENV_MODE === 'docker' ? 'kafka:9093' : 'localhost:9092';
    const redisPassword = secrets.REDIS_PASSWORD || 'changeme';
    const redisUrl = `redis://:${redisPassword}@${redisHost}:6379`;

    envContent += `# Redis Configuration
REDIS_HOST=${redisHost}
REDIS_PORT=6379
REDIS_PASSWORD=${redisPassword}
REDIS_URL=${redisUrl}

# Kafka Configuration
KAFKA_BROKERS=${kafkaBrokers}
KAFKA_CLIENT_ID=${serviceName}
KAFKA_GROUP_ID=${serviceName}-group

# JWT Configuration
JWT_ACCESS_SECRET=${secrets.JWT_ACCESS_SECRET || 'changeme-access-secret'}
JWT_REFRESH_SECRET=${secrets.JWT_REFRESH_SECRET || 'changeme-refresh-secret'}

# Logging
LOG_LEVEL=debug
LOG_DIR=./logs

# API Gateway
API_GATEWAY_URL=http://localhost:8000

# External Base URL (used for webhooks)
APP_BASE_URL=${secrets.APP_BASE_URL || secrets.API_GATEWAY_URL || 'http://localhost:8000'}

`;

    // Cloudinary for media-service
    if (serviceName === 'media-service') {
        envContent += `# Cloudinary Configuration
CLOUDINARY_CLOUD_NAME=${secrets.CLOUDINARY_CLOUD_NAME || 'your-cloud-name'}
CLOUDINARY_API_KEY=${secrets.CLOUDINARY_API_KEY || 'your-api-key'}
CLOUDINARY_API_SECRET=${secrets.CLOUDINARY_API_SECRET || 'your-api-secret'}
`;
    }

    // Service-specific internal URLs for API Gateway
    if (serviceName === 'api-gateway') {
        const authHost = ENV_MODE === 'docker' ? 'auth-service' : 'localhost';
        const notificationHost = ENV_MODE === 'docker' ? 'notification-service' : 'localhost';
        const chatHost = ENV_MODE === 'docker' ? 'chat-service' : 'localhost';
        const mediaHost = ENV_MODE === 'docker' ? 'media-service' : 'localhost';
        const subscriptionHost = ENV_MODE === 'docker' ? 'subscription-service' : 'localhost';

        envContent += `
# Internal Service URLs
AUTH_SERVICE_URL=http://${authHost}:3001
NOTIFICATION_SERVICE_URL=http://${notificationHost}:3008
CHAT_SERVICE_URL=http://${chatHost}:3012
MEDIA_SERVICE_URL=http://${mediaHost}:3011
SUBSCRIPTION_SERVICE_URL=http://${subscriptionHost}:3003

`;
    }

    if (serviceName === 'subscription-service') {
        envContent += `
# Subscription Service Specific
STRIPE_SECRET_KEY=${secrets.STRIPE_SECRET_KEY || 'sk_test_changeme'}
PAYPAL_CLIENT_SECRET=${secrets.PAYPAL_CLIENT_SECRET || 'changeme'}
MARKETPLACE_COMMISSION_RATE=0.15

# payunit Service Specific
PAYUNIT_BASE_URL=${secrets.PAYBASE_URL || 'https://gateway.payunit.net'}
PAYUNIT_API_KEY=${secrets.PAYUNIT_API_KEY}
PAYUNIT_API_USERNAME=${secrets.PAYUNIT_API_USERNAME}
PAYUNIT_API_PASSWORD=${secrets.PAYUNIT_API_PASSWORD}
PAYUNIT_MODE=${secrets.PAYUNIT_MODE || 'test'}
PAYUNIT_TIMEOUT=${secrets.PAYUNIT_TIMEOUT || 10000}
PAYUNIT_DEFAULT_CURRENCY=${secrets.PAYUNIT_DEFAULT_CURRENCY || 'XAF'}
PAYUNIT_DEFAULT_COUNTRY=${secrets.PAYUNIT_DEFAULT_COUNTRY || 'CM'}
`;
    }

    if (serviceName === 'media-service') {
        envContent += `
# Media Service Specific
AWS_ACCESS_KEY_ID=your_aws_access_key
AWS_SECRET_ACCESS_KEY=${secrets.AWS_SECRET_ACCESS_KEY || 'changeme'}
AWS_S3_BUCKET=marketplace-media
CDN_URL=https://cdn.marketplace.com
MAX_FILE_SIZE=10485760
ALLOWED_FILE_TYPES=image/jpeg,image/png,image/gif,application/pdf
`;
    }

    if (serviceName === 'notification-service') {
        envContent += `
# Notification Service Specific
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USER=noreply@marketplace.com
SMTP_PASSWORD=changeme
EMAIL_FROM=noreply@marketplace.com
TWILIO_AUTH_TOKEN=${secrets.TWILIO_AUTH_TOKEN || 'changeme'}
`;
    }

    const serviceDir = path.join(ROOT_DIR, 'services', serviceName);
    if (!fs.existsSync(serviceDir)) {
        fs.mkdirSync(serviceDir, { recursive: true });
    }

    const envPath = path.join(serviceDir, '.env');
    fs.writeFileSync(envPath, envContent);
    console.log(`✓ Created services/${serviceName}/.env`);
}

/**
 * Generate .gitignore
 */
function generateGitignore() {
    const gitignoreContent = `# Dependencies
node_modules/
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Environment files
.env
.env.local
.env.*.local
.secrets.env
*.env

# Logs
logs/
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# OS files
.DS_Store
Thumbs.db

# IDE
.vscode/
.idea/
*.swp
*.swo
*~

# Docker
docker-compose.override.yml

# Build outputs
dist/
build/
*.tsbuildinfo

# Testing
coverage/
.nyc_output/

# Temporary files
tmp/
temp/
*.tmp
`;

    const gitignorePath = path.join(ROOT_DIR, '.gitignore');
    fs.writeFileSync(gitignorePath, gitignoreContent);
    console.log('✓ Created .gitignore');
}

/**
 * Generate .dockerignore
 */
function generateDockerignore() {
    const dockerignoreContent = `node_modules
npm-debug.log
.env
.env.*
.secrets.env
.git
.gitignore
README.md
*.md
logs
*.log
coverage
.nyc_output
dist
build
.vscode
.idea
*.swp
*.swo
*~
.DS_Store
Thumbs.db
`;

    const dockerignorePath = path.join(ROOT_DIR, '.dockerignore');
    fs.writeFileSync(dockerignorePath, dockerignoreContent);
    console.log('✓ Created .dockerignore');
}

/**
 * Main execution
 */
function main() {
    console.log('\n' + '='.repeat(60));
    console.log('⚙️  MARKETPLACE PLATFORM - ENVIRONMENT SETUP');
    console.log('='.repeat(60) + '\n');

    try {
        // Load secrets
        const secrets = loadSecrets();

        // Generate root environment
        console.log('📝 Generating root configuration...\n');
        generateRootEnv(secrets);
        generateGitignore();
        generateDockerignore();

        // Generate service environments
        console.log('\n📦 Generating service configurations...\n');
        Object.entries(SERVICE_CONFIGS).forEach(([serviceName, config]) => {
            generateServiceEnv(serviceName, config, secrets);
        });

        console.log('\n' + '='.repeat(60));
        console.log('✅ Environment setup completed!');
        console.log('='.repeat(60));

        console.log('\n📝 Next steps:');
        console.log('  1. Review and update .env files with your credentials');
        console.log('  2. Update SMTP, Stripe, PayPal, AWS credentials');
        console.log('  3. Run: npm run install:all');
        console.log('  4. Run: npm run docker:dev\n');

    } catch (error) {
        console.error('\n❌ Error setting up environment:', error.message);
        process.exit(1);
    }
}

// Run if called directly
if (require.main === module) {
    main();
}

module.exports = { main, generateRootEnv, generateServiceEnv };
